[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "psenv"
version = "0.17.1"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"python-dotenv==0.20.0",
	"pyaml==21.10.1",
	"boto3==1.20.49",
	"boto3-stubs[ssm]==1.36.6",
	"ramjam==0.5.0"
]

[project.optional-dependencies]
dev = [
	"setuptools==75.8.0",
	"build==1.2.2",
	"pytest==8.3.4",
	"ruff==0.9.3",
	"python-semantic-release==9.17.0"
]


[project.scripts]
psenv = "psenv.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = [
	"E", # pycodestyle errors
	"I", # isort
	"F", # pyflakes
]
